GoL: main.cpp gameengine.cpp introstate.cpp menustate.cpp playstate.cpp gol.cpp
	g++ main.cpp gameengine.cpp introstate.cpp menustate.cpp playstate.cpp gol.cpp -o GoL -lmingw32 -lSDLmain -lSDL -lSDL_image -lSDL_ttf -static-libgcc -static-libstdc++
